const products=[
{id:'p1',name:'Noise Pro X Wireless Headphones',shop:'Sony Official',cat:'Điện tử',art:'🎧',price:3290000,old:4590000,rating:4.9,sold:'2.1k',mall:true,discount:28,delivery:'Giao miễn phí ngày mai'},
{id:'p2',name:'Glow Barrier Repair Serum 30ml',shop:'Laneige Official',cat:'Làm đẹp',art:'🧴',price:589000,old:720000,rating:4.8,sold:'8.4k',mall:true,discount:18,delivery:'Freeship'},
{id:'p3',name:'Halo Ambient Desk Lamp',shop:'Mori Living',cat:'Nhà cửa',art:'💡',price:749000,old:990000,rating:4.7,sold:'924',discount:24,delivery:'Giao trong 2 ngày'},
{id:'p4',name:'Cloud Runner Everyday Sneakers',shop:'Motion Lab',cat:'Thời trang',art:'👟',price:1390000,old:1690000,rating:4.9,sold:'3.8k',discount:18,delivery:'Freeship'},
{id:'p5',name:'Compact Smart Air Purifier S2',shop:'Dyson Select',cat:'Gia dụng',art:'🌬️',price:3990000,old:4690000,rating:4.8,sold:'1.3k',mall:true,discount:15,delivery:'Giao miễn phí'},
{id:'p6',name:'Minimal Everyday Backpack 18L',shop:'Nomad Studio',cat:'Phụ kiện',art:'🎒',price:679000,old:850000,rating:4.7,sold:'5.2k',discount:20,delivery:'Freeship'},
{id:'p7',name:'Mechanical Keyboard 75% Violet',shop:'Keyhaus',cat:'Điện tử',art:'⌨️',price:1590000,old:1890000,rating:4.9,sold:'2.7k',discount:16,delivery:'Giao ngày mai'},
{id:'p8',name:'Ceramic Aroma Diffuser Set',shop:'Soft Home',cat:'Nhà cửa',art:'🏺',price:429000,old:520000,rating:4.6,sold:'1.9k',discount:17,delivery:'Freeship'},
{id:'p9',name:'Hydrating Daily Sunscreen SPF50+',shop:'Beauty Lab',cat:'Làm đẹp',art:'🧴',price:349000,old:420000,rating:4.8,sold:'12k',discount:17,delivery:'Giao hôm nay'},
{id:'p10',name:'Studio Oversized Cotton Shirt',shop:'Atelier Select',cat:'Thời trang',art:'👕',price:899000,old:1090000,rating:4.7,sold:'1.4k',mall:true,discount:17,delivery:'Freeship'},
{id:'p11',name:'Portable Speaker Mini 2',shop:'Audio Corner',cat:'Điện tử',art:'🔊',price:799000,old:990000,rating:4.7,sold:'6.2k',discount:19,delivery:'Giao ngày mai'},
{id:'p12',name:'Daily Brew Ceramic Mug Set',shop:'Table Story',cat:'Nhà cửa',art:'☕',price:289000,old:360000,rating:4.8,sold:'4.4k',discount:20,delivery:'Freeship'}
];
const categories=[['📱','Điện tử','12.4K sản phẩm'],['💄','Làm đẹp','8.9K sản phẩm'],['👕','Thời trang','24K sản phẩm'],['🛋️','Nhà cửa','11.2K sản phẩm'],['⚽','Thể thao','6.4K sản phẩm'],['🧸','Mẹ & Bé','7.8K sản phẩm'],['🥑','Bách hóa','5.1K sản phẩm'],['📚','Sách & Văn phòng','3.9K sản phẩm']];
const money=n=>new Intl.NumberFormat('vi-VN').format(n)+' ₫';
const cartKey='violet-cart-v1';
const getCart=()=>{try{return JSON.parse(localStorage.getItem(cartKey)||'[]')}catch{return[]}};
const saveCart=cart=>{localStorage.setItem(cartKey,JSON.stringify(cart));updateCartCount()};
const updateCartCount=()=>{const count=getCart().reduce((a,b)=>a+(b.qty||1),0);document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=count)};
const toast=msg=>{const el=document.getElementById('toast');if(!el)return;el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)};
function productCard(p){return `<article class="product-card"><a class="product-media" href="./product.html?id=${p.id}">${p.mall?'<span class="mall-badge">VIOLET MALL</span>':`<span class="discount-badge">-${p.discount}%</span>`}<button class="heart-btn" type="button" aria-label="Lưu sản phẩm">♡</button><span class="product-art">${p.art}</span></a><div class="product-info"><span class="product-shop">${p.shop}${p.mall?' · ✓':''}</span><h3><a href="./product.html?id=${p.id}">${p.name}</a></h3><div class="product-meta"><span class="rating">★ ${p.rating}</span><span>${p.sold} đã bán</span></div><div class="price-line"><strong>${money(p.price)}</strong><del>${money(p.old)}</del></div><div class="delivery">${p.delivery}</div><button class="add-btn" data-add="${p.id}">Thêm vào giỏ</button></div></article>`}
function bindAddButtons(){document.querySelectorAll('[data-add]').forEach(btn=>btn.addEventListener('click',()=>{const id=btn.dataset.add;const cart=getCart();const item=cart.find(x=>x.id===id);if(item)item.qty+=1;else cart.push({id,qty:1});saveCart(cart);toast('Đã thêm sản phẩm vào giỏ')}))}
function initHome(){const cg=document.getElementById('categoryGrid');if(cg)cg.innerHTML=categories.map(c=>`<a class="category-card" href="./search.html?q=${encodeURIComponent(c[1])}"><div class="category-visual">${c[0]}</div><b>${c[1]}</b><small>${c[2]}</small></a>`).join('');const flash=document.getElementById('flashProducts');if(flash)flash.innerHTML=products.slice(0,5).map(productCard).join('');const rec=document.getElementById('recommendProducts');if(rec)rec.innerHTML=products.slice(4,12).map(productCard).join('');bindAddButtons();document.querySelectorAll('[data-feed]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-feed]').forEach(x=>x.classList.remove('active'));b.classList.add('active');let set=products;if(b.dataset.feed==='under')set=products.filter(p=>p.price<500000);if(b.dataset.feed==='new')set=[...products].reverse();if(rec)rec.innerHTML=set.slice(0,8).map(productCard).join('');bindAddButtons()}));let sec=2*3600+14*60+38;setInterval(()=>{sec=Math.max(0,sec-1);const h=String(Math.floor(sec/3600)).padStart(2,'0'),m=String(Math.floor(sec%3600/60)).padStart(2,'0'),s=String(sec%60).padStart(2,'0');document.querySelectorAll('[data-countdown]').forEach(el=>el.textContent=`${h}:${m}:${s}`)},1000)}
function initSearchBox(){const input=document.getElementById('searchInput'),box=document.getElementById('searchSuggest');if(!input||!box)return;const render=()=>{const q=input.value.trim().toLowerCase();const base=q?products.filter(p=>(p.name+p.shop+p.cat).toLowerCase().includes(q)).slice(0,5):products.slice(0,4);box.innerHTML=base.map(p=>`<a class="suggest-item" href="./product.html?id=${p.id}"><b>${p.art}</b><div><strong>${p.name}</strong><small>${p.shop}</small></div><span>${money(p.price)}</span></a>`).join('')+(q?`<a class="suggest-item" href="./search.html?q=${encodeURIComponent(input.value)}"><b>⌕</b><strong>Xem tất cả kết quả cho “${input.value}”</strong><span>→</span></a>`:'');box.classList.toggle('open',document.activeElement===input)};input.addEventListener('input',render);input.addEventListener('focus',render);document.addEventListener('click',e=>{if(!e.target.closest('.search-box'))box.classList.remove('open')})}
function initSearchPage(){const grid=document.getElementById('plpGrid'),title=document.getElementById('searchTitle'),count=document.getElementById('resultCount');if(!grid)return;const q=new URLSearchParams(location.search).get('q')||'';let list=q?products.filter(p=>(p.name+p.shop+p.cat).toLowerCase().includes(q.toLowerCase())):products;if(!list.length)list=products;if(title)title.textContent=q?`Kết quả cho “${q}”`:'Tất cả sản phẩm';if(count)count.textContent=`${list.length} sản phẩm phù hợp`;grid.innerHTML=list.map(productCard).join('');bindAddButtons();document.querySelectorAll('[data-cat-filter]').forEach(c=>c.addEventListener('change',()=>{const cats=[...document.querySelectorAll('[data-cat-filter]:checked')].map(x=>x.value);const filtered=cats.length?products.filter(p=>cats.includes(p.cat)):list;grid.innerHTML=filtered.map(productCard).join('');if(count)count.textContent=`${filtered.length} sản phẩm phù hợp`;bindAddButtons()}))}
function initProduct(){const root=document.getElementById('pdpRoot');if(!root)return;const id=new URLSearchParams(location.search).get('id')||'p1';const p=products.find(x=>x.id===id)||products[0];root.innerHTML=`<div class="breadcrumb"><a href="./index.html">Home</a> / <a href="./search.html?q=${encodeURIComponent(p.cat)}">${p.cat}</a> / ${p.name}</div><div class="pdp-grid"><div><div class="gallery-main">${p.art}</div><div class="gallery-thumbs"><button class="active">${p.art}</button><button>◫</button><button>◇</button><button>＋</button></div></div><div class="pdp-info"><p class="eyebrow">${p.mall?'VIOLET MALL · CHÍNH HÃNG':p.cat}</p><h1>${p.name}</h1><div class="pdp-statline"><span>★ ${p.rating}</span><span>1.2K đánh giá</span><span>${p.sold} đã bán</span></div><div class="pdp-price">${money(p.price)} <del>${money(p.old)}</del></div><div class="save-label">Tiết kiệm ${money(p.old-p.price)} · -${p.discount}%</div><div class="deal-box"><strong>Ưu đãi tốt nhất hôm nay</strong><span class="voucher-pill">VIOLET100 · Giảm thêm 100K</span></div><div class="option-group"><div class="option-label">Phiên bản</div><div class="option-list"><button class="option-btn active">Standard</button><button class="option-btn">Plus</button><button class="option-btn">Premium</button></div></div><div class="delivery-box"><b>🚚</b><div><strong>${p.delivery}</strong><br><small>Đến TP. Hồ Chí Minh · Miễn phí vận chuyển</small></div></div><div class="buy-actions"><button class="btn btn-soft" data-add="${p.id}">Thêm vào giỏ</button><button class="btn btn-primary" id="buyNow">Mua ngay</button></div><div class="seller-card"><div class="seller-avatar">V</div><div class="seller-meta"><h3>${p.shop} ${p.mall?'✓':''}</h3><p>Shop được Violet xác minh · phản hồi trong 1 giờ</p><div class="seller-stats"><span>★ 4.9</span><span>98% tích cực</span><span>12K theo dõi</span></div></div><a class="btn btn-outline" href="#">Xem shop</a></div></div></div><div class="pdp-lower"><div class="detail-copy"><p class="eyebrow">CHI TIẾT SẢN PHẨM</p><h2>Mọi thông tin bạn cần trước khi quyết định.</h2><p>Thiết kế phần thông tin theo hướng answer-first: thông số quan trọng, bảo hành, đổi trả và nguồn gốc được đặt gần quyết định mua thay vì giấu trong tab sâu.</p><table class="spec-table"><tr><td>Thương hiệu</td><td>${p.shop.replace(' Official','')}</td></tr><tr><td>Danh mục</td><td>${p.cat}</td></tr><tr><td>Bảo hành</td><td>12 tháng</td></tr><tr><td>Đổi trả</td><td>15 ngày với Violet Mall</td></tr><tr><td>Xuất xứ</td><td>Thông tin đã xác minh</td></tr></table></div><aside class="checkout-card"><p class="eyebrow">BUYER PROTECTION</p><h2>Mua hàng an tâm hơn</h2><p>Violet giữ thanh toán an toàn cho đến khi đơn hàng được xác nhận giao thành công.</p></aside></div>`;bindAddButtons();document.getElementById('buyNow')?.addEventListener('click',()=>{const cart=getCart();const item=cart.find(x=>x.id===p.id);if(item)item.qty+=1;else cart.push({id:p.id,qty:1});saveCart(cart);location.href='./cart.html'})}
function cartDetailed(){return getCart().map(i=>({...i,p:products.find(p=>p.id===i.id)})).filter(x=>x.p)}
function initCart(){const root=document.getElementById('cartItems');if(!root)return;const render=()=>{const items=cartDetailed();const groups=Object.groupBy?Object.groupBy(items,x=>x.p.shop):items.reduce((a,x)=>((a[x.p.shop]??=[]).push(x),a),{});root.innerHTML=items.length?Object.entries(groups).map(([shop,arr])=>`<section class="cart-shop"><div class="cart-shop-head"><input type="checkbox" checked> <strong>${shop}</strong><span>✓</span></div>${arr.map(({p,qty})=>`<div class="cart-item"><div class="cart-art">${p.art}</div><div><h3>${p.name}</h3><p>Standard · Chính sách đổi trả áp dụng</p><div class="qty-row"><button data-qty="${p.id}" data-delta="-1">−</button><span>${qty}</span><button data-qty="${p.id}" data-delta="1">+</button></div></div><div class="cart-item-price"><strong>${money(p.price*qty)}</strong><p>${p.delivery}</p></div></div>`).join('')}</section>`).join(''):`<div class="checkout-card"><h2>Giỏ hàng đang trống</h2><p>Khám phá sản phẩm phù hợp và thêm vào đây để tiếp tục.</p><a class="btn btn-primary" href="./index.html">Tiếp tục mua sắm</a></div>`;document.querySelectorAll('[data-qty]').forEach(b=>b.addEventListener('click',()=>{let cart=getCart(),it=cart.find(x=>x.id===b.dataset.qty);if(!it)return;it.qty+=Number(b.dataset.delta);cart=cart.filter(x=>x.qty>0);saveCart(cart);render();renderSummary()}));renderSummary()};render()}
function renderSummary(){const items=cartDetailed();const subtotal=items.reduce((s,x)=>s+x.p.price*x.qty,0),shipping=items.length?30000:0,discount=items.length?Math.min(100000,subtotal):0,total=Math.max(0,subtotal+shipping-discount);document.querySelectorAll('[data-subtotal]').forEach(e=>e.textContent=money(subtotal));document.querySelectorAll('[data-shipping]').forEach(e=>e.textContent=money(shipping));document.querySelectorAll('[data-discount]').forEach(e=>e.textContent='-'+money(discount));document.querySelectorAll('[data-total]').forEach(e=>e.textContent=money(total))}
function initCheckout(){const root=document.getElementById('checkoutProducts');if(!root)return;const items=cartDetailed();root.innerHTML=items.map(({p,qty})=>`<div class="cart-item"><div class="cart-art">${p.art}</div><div><h3>${p.name}</h3><p>${p.shop} · x${qty}</p></div><div class="cart-item-price"><strong>${money(p.price*qty)}</strong></div></div>`).join('')||'<p>Chưa có sản phẩm trong đơn.</p>';renderSummary();document.getElementById('placeOrder')?.addEventListener('click',()=>{if(!items.length)return toast('Giỏ hàng đang trống');localStorage.removeItem(cartKey);updateCartCount();toast('Đặt hàng thành công · VIOLET-0909');setTimeout(()=>location.href='./index.html',1300)})}
updateCartCount();initSearchBox();const page=document.body.dataset.page;if(page==='home')initHome();if(page==='search')initSearchPage();if(page==='product')initProduct();if(page==='cart')initCart();if(page==='checkout')initCheckout();